[package]
name = "gitfugue"
version = "0.2.0"
edition = "2024"

[dependencies]
anyhow = "1.0.103"
clap = { version = "4.6.1", features = ["derive"] }
midly = "0.5.3"
tree-sitter = "0.26.10"
tree-sitter-javascript = "0.25.0"
tree-sitter-python = "0.25.0"
tree-sitter-rust = "0.24.2"

[dev-dependencies]
tempfile = "3.27.0"
